### ISSUE TITLE
Updating gitfs_remotes requires root access

### ISSUE THREAD

**Issue by WilCrofter** [alexander-bauer/caf-1222-salt#14]
Just a note that root access is required to execute
```
salt-call state.apply salt.master
```
This is not necessarily a problem, but may require coordination between admin and periphery.

**Comment by alexander-bauer** [comment]
All `salt` directives will need root.

**Comment by WilCrofter** [comment]
Of course. But the pair of directives necessary to enact a gitfs_remotes access requires root on at least two machines, master and minion, and a contributor such as myself may not have access on both :-D . As I say, this is not necessarily a problem, but may require coordination.

**Comment by alexander-bauer** [comment]
Right. Root access should be consistent across all minions (it's not yet, but it *should* be). All users should be configured using `users-formula`, as mentioned in #15.

**Comment by WilCrofter** [comment]
OK. Of course root at salt-master could issue `state.apply` to relevant minions which would require less coordination. Closing this issue.
